[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.5.16"
optimizer = true
optimizer_runs = 1000000
# optimizer_runs = 200 # default

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
